# TODO: init script, configuration etc.
Summary:	WvTFTPd - Trivial File Transfer Protocol server
Summary(pl.UTF-8):	WvTFTPd - serwer TFTP (Trivial File Transfer Protocol)
Name:		wvtftp
Version:	1.0.1
Release:	0.1
License:	LGPL v2.1+
Group:		Networking/Daemons
Source0:	http://wvstreams.googlecode.com/files/%{name}-%{version}.tar.gz
# Source0-md5:	dd32fdc1bb2f78cfc0c2805ff1210b0d
# is there more specific URL? alumnit.ca shows HTTP 500 currently
URL:		http://alumnit.ca/wiki/
BuildRequires:	libstdc++-devel
BuildRequires:	pkgconfig
BuildRequires:	wvstreams-devel >= 4.5
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
WvTFTPd - Trivial File Transfer Protocol server.

%description -l pl.UTF-8
WvTFTPd - serwer TFTP (Trivial File Transfer Protocol).

%prep
%setup -q

%build
# not autoconf generated, no arguments used
./configure
# not generated by configure (and not needed now)
touch config.mk
%{__make} -j1 \
	CC="%{__cc}" \
	CXX="%{__cxx}" \
	CPPOPTS="%{rpmcppflags}" \
	COPTS="%{rpmcflags}" \
	CXXOPTS="%{rpmcppflags}" \
	VERBOSE=1 \
	WVSTREAMS_LIB=. \
	enable_debug=no

%install
rm -rf $RPM_BUILD_ROOT
%{__make} install \
	PREFIX=$RPM_BUILD_ROOT%{_prefix} \
	BINDIR=$RPM_BUILD_ROOT%{_sbindir} \
	MANDIR=$RPM_BUILD_ROOT%{_mandir}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc ChangeLog README
%attr(755,root,root) %{_sbindir}/wvtftpd
%{_mandir}/man8/wvtftpd.8*
